### ISSUE TITLE
I can't compile code

### ISSUE THREAD

**Issue by josepablog** [archagon/tasty-imitation-keyboard#76] opened 2015-04-11 17:31 UTC
I'm a newbie in  Swift, but I can't compile this project. Is it my fault, or is there something wrong with the code? =-)

![screen shot 2015-04-11 at 1 30 20 pm](https://cloud.githubusercontent.com/assets/1832193/7102434/fe626e52-e04e-11e4-9eab-1d08318d89dc.png)

**Comment by tkersey** [comment] 2015-04-11 22:30
@josepablog You're using Xcode 6.3 which includes Swift 1.2. This project hasn't been updated to Swift 1.2 yet. You can either make the conversions to Swift 1.2 yourself or download Xcode 6.2 from the [Apple Developer Downloads site](http://developer.apple.com/downloads).

I converted the project over to Swift 1.2 myself. The changes you would need to make are probably not obvious if you're new to Swift. Then again it might be a good way to get familiar with Swift :smile:. Xcode 6.3 has a tool to convert to Swift 1.2. It's under Edit -> Convert -> To Latest Swift Syntax.... Unfortunately it doesn't handle all of the changes. You will have compile errors after running that you'll have to figure out.

**Comment by archagon** [comment] 2015-04-11 22:56
I'll get this fixed in the next few days.

**Comment by 1000000000000** [comment] 2015-04-15 16:28
I'm new to Swift and figured out how to fix most of the bugs, but couldn't quite get all of them worked out. I look forward to your updated version. Thanks!

**Comment by PrasiNV** [comment] 2015-04-15 22:08
First of all, a ton of thanks for this wonderful work !!!

I am new to swift. Created a custom keyboard using this source code. Everything was perfect and tested thoroughly on iOS 8.2. I even got an app released on app store just 2 days before iOS 8.3 public release. Now my keyboard faces a weird issue while changing between landscape and portrait modes. Keyboard just crashes while changing interface orientations.

I tried converting to latest swift syntax - but unsuccessful as of now. But I did notice couple of errors related to interface orientation too. I am figuring out how to fix and look forward for your updated version.

Thanks

**Comment by archagon** [comment] 2015-04-15 23:35
OK, I pushed an update with all the 8.3 fixes. @PrasiNV I could not reproduce any interface orientation errors. Let me know if they still persist with the latest commit.

**Closed by archagon** 2015-04-15 23:35 UTC

**Comment by archagon** [comment] 2015-04-15 23:58
OK, I see the graphical glitches now. Don't get any crashes, though. Where are you crashing?

**Comment by PrasiNV** [comment] 2015-04-16 22:07
I set the deployment target as 8.2 and released on the app store. I checked the app store binary on 8.2 - It is all fine. Then checked it on 8.3. Everytime keyboard turns into landscape mode, the keyboard crashed. Tapping the globe key while keeping the device in landscape reopened the keyboard. Now If I turn it into portrait mode then again it crashes.

Today I successfully updated the swift syntax in xcode 6.3. Interestingly, updated syntax binary doesn't crash when changing orientation.

By the way, after updating to latest swift syntax, I ended up with warning related to interfaceorientation method deprecated in ios 8.0. Is there any fix for this ?

**Comment by archagon** [comment] 2015-04-16 22:12
Yeah, I'm not sure why you were seeing the crashes. I can't reproduce it on any of my 8.2-compiled App Store apps, unfortunately.

As for the warnings, they're no big deal. I'll remove them eventually as part of the ultimate fix for the graphics glitches.

**Comment by PrasiNV** [comment] 2015-04-16 22:36
This might not be the correct place, but I am facing another issue as well in iOS 8.3:

Surprisingly, the globe icon to change keyboards doesn't appear in spotlight search. However it appears in any other stock iOS app. Any pointers ?

**Comment by pirrate** [comment] 2015-04-17 05:38
@PrasiNV just restart your device it will be fixed.
